from tools.llm_router import safe_print
import os
import re
from pathlib import Path
from datetime import datetime

def format_report(title: str, content: str) -> str:
    """Adds a standardized header to the markdown report."""
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"# {title}\n"
    header += f"**Date:** {date_str} | **Generated by Forge**\n"
    header += "-" * 40 + "\n\n"
    return header + content

def save_report(content: str, project_slug: str, filename: str) -> str:
    """Saves the content to the project's output directory."""
    output_dir = Path(f"outputs/{project_slug}")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    file_path = output_dir / filename
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    safe_print(f"Saved: {file_path}")
    return str(file_path)

def get_project_slug(idea: str) -> str:
    """Generates a lowercase, hyphenated slug from the first 3 meaningful words."""
    # Remove common filler words and non-alphanumeric characters
    fillers = {"i", "want", "to", "build", "a", "an", "the", "that", "helps", "for"}
    clean_text = re.sub(r'[^a-zA-Z0-9\s]', '', idea).lower()
    words = [w for w in clean_text.split() if w not in fillers]
    
    # Fallback if all words were fillers
    if not words:
        words = clean_text.split()[:3]
        
    slug = "-".join(words[:3])
    return slug if slug else "untitled-project"

def compile_full_report(state: dict) -> str:
    """Combines all 5 phase outputs into one master markdown document."""
    full_report = "# FORGE MASTER REPORT\n\n"
    full_report += f"**Project:** {state.get('user_idea', 'Untitled')}\n"
    full_report += f"**Slug:** {state.get('project_slug', 'N/A')}\n\n"
    
    phases = [
        ("Phase 1: Idea Analysis", "idea_analysis"),
        ("Phase 2: Market Research", "market_research"),
        ("Phase 3: Verdict", "verdict"),
        ("Phase 4: Technical R&D", "technical_rd"),
        ("Phase 5: Dev Blueprint", "blueprint")
    ]
    
    for title, key in phases:
        content = state.get(key, "")
        if isinstance(content, dict): # For verdict dict
            content = content.get("report", "")
            
        full_report += f"## {title}\n"
        full_report += f"{content}\n\n"
        full_report += "---\n\n"
        
    return full_report