from tools.llm_router import safe_print
import os
from pathlib import Path
from datetime import datetime

def generate_env_template(tech_stack: list) -> str:
    """Generates a .env.example file content string based on tech stack."""
    content = "# Project Environment Variables\n"
    content += f"# Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    content += "APP_ENV=development\n"
    content += "PORT=3000\n"
    content += "DEBUG=True\n\n"
    
    # Normalize tech stack to lowercase for matching
    stack = [item.lower() for item in tech_stack]
    
    mapping = {
        "supabase": "SUPABASE_URL=\nSUPABASE_ANON_KEY=\n",
        "tavily": "TAVILY_API_KEY=tvly-YOUR_KEY\n",
        "openai": "OPENAI_API_KEY=sk-YOUR_KEY\n",
        "firebase": "FIREBASE_API_KEY=\nFIREBASE_PROJECT_ID=\n",
        "mongodb": "MONGODB_URI=mongodb+srv://\n",
        "postgresql": "DATABASE_URL=postgresql://user:pass@localhost:5432/dbname\n",
        "jwt": "JWT_SECRET=your-secret-key-min-32-chars\n",
        "postman": "# Postman variables not required in .env\n",
        "react": "# React frontend variables (if any)\nREACT_APP_API_URL=http://localhost:3000\n",
        "node": "# Node.js backend variables\n",
        "python": "# Python environment variables\n",
        "ollama": "OLLAMA_BASE_URL=http://localhost:11434\nOLLAMA_MODEL=llama3.1:8b\n"
    }
    
    for key, env_vars in mapping.items():
        if any(key in s for s in stack):
            content += f"# {key.capitalize()} Configuration\n"
            content += env_vars + "\n"
            
    return content

def generate_gitignore(tech_stack: list) -> str:
    """Returns a .gitignore content string based on tech stack."""
    content = "# System files\n.DS_Store\nThumbs.db\n\n"
    content += "# Environment and secrets\n.env\n.env.local\n.env.*.local\n\n"
    content += "# Dependencies and logs\nnode_modules/\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\nlogs\n*.log\n\n"
    content += "# Compilations and builds\n__pycache__/\n*.pyc\n*.pyo\n*.pyd\n.Python\nbuild/\ndevelop-eggs/\ndist/\ndownloads/\neggs/\n.eggs/\nlib/\nlib64/\nparts/\nsbin/\nvar/\nbin/\ninclude/\nshare/\n*.egg-info/\n.installed.cfg\n*.egg\nMANIFEST\n\n"
    
    stack = [item.lower() for item in tech_stack]
    
    if any(s in ["python", "django", "flask", "fastapi"] for s in stack):
        content += "# Python specific\nvenv/\n.venv/\nenv/\n.env/\nENV/\nbin/\n\n"
        
    if any(s in ["react", "nextjs", "vue", "angular", "node"] for s in stack):
        content += "# Web specific\n.next/\n.nuxt/\nout/\n.cache/\n.parcel-cache/\n.eslintcache\n.stylelintcache\n\n"
        
    return content

def generate_readme_skeleton(project_name: str, idea_summary: str, tech_stack: list) -> str:
    """Returns a README.md skeleton."""
    content = f"# {project_name}\n\n"
    content += f"> {idea_summary}\n\n"
    
    content += "## 🛠 Tech Stack\n\n"
    content += "| Category | Technology |\n"
    content += "| :--- | :--- |\n"
    
    # Simple categorization logic
    for item in tech_stack:
        content += f"| Support | {item} |\n"
    
    content += "\n## 🚀 Quick Start\n\n"
    content += "### Prerequisites\n- List your prerequisites here (e.g., Node.js, Python, Docker)\n\n"
    content += "### Installation\n```bash\n# Example commands\ngit clone <repo-url>\ncd " + project_name.lower().replace(" ", "-") + "\n# Install dependencies\n```\n\n"
    
    content += "## 📁 Project Structure\n\n"
    content += "```text\n(Structure will be defined by Forge Development Blueprint)\n```\n\n"
    
    content += "## 🤝 Contributing\nContributions are welcome! Please read the contributing guidelines.\n"
    
    return content

def generate_git_commands(project_name: str) -> str:
    """Returns the exact shell commands to initialize Git."""
    repo_name = project_name.lower().replace(" ", "-")
    content = f"# Run these commands in your project root:\n\n"
    content += "git init\n"
    content += "git add .\n"
    content += "git commit -m \"Initial commit: Project scaffold generated by FORGE\"\n"
    content += "git branch -M main\n\n"
    content += "# To connect to GitHub:\n"
    content += f"# git remote add origin https://github.com/YOUR_USERNAME/{repo_name}.git\n"
    content += "# git push -u origin main\n"
    
    return content

def generate_all_scaffold(project_name: str, idea_summary: str, tech_stack: list, output_dir: str) -> dict:
    """Generates all 4 scaffold files and saves them."""
    scaffold_dir = Path(output_dir) / "scaffold"
    scaffold_dir.mkdir(parents=True, exist_ok=True)
    
    files = {
        ".env.example": generate_env_template(tech_stack),
        ".gitignore": generate_gitignore(tech_stack),
        "README.md": generate_readme_skeleton(project_name, idea_summary, tech_stack),
        "setup_git.sh": generate_git_commands(project_name)
    }
    
    for filename, content in files.items():
        with open(scaffold_dir / filename, "w", encoding="utf-8") as f:
            f.write(content)
            
    safe_print(f"Scaffold files generated in: {scaffold_dir}")
    return files

if __name__ == "__main__":
    # Test sample inputs
    p_name = "ReportPilot"
    i_summary = "An AI-powered tool that auto-generates weekly engineering reports from Git commits and Jira tickets."
    t_stack = ["Next.js", "FastAPI", "Supabase", "JWT", "Tavily", "Python"]
    o_dir = "test_outputs"
    
    safe_print("Testing Scaffold Generator...")
    results = generate_all_scaffold(p_name, i_summary, t_stack, o_dir)
    
    for fname, fcontent in results.items():
        safe_print(f"\n--- {fname} ---")
        safe_print(fcontent[:200] + "..." if len(fcontent) > 200 else fcontent)